FROM registry.opensuse.org/opensuse/tumbleweed:latest AS build

RUN mkdir /sysroot && \
    zypper --gpg-auto-import-keys --installroot /sysroot refresh && \
    zypper --non-interactive --installroot /sysroot install -y rtl-sdr

FROM scratch AS final
USER 65532:65532
COPY --from=build /sysroot /
