resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: frallan/k8s-radio
  newTag: 0.0.6

configMapGenerator:
- envs:
  - .env
  name: manager-config
