---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - radio.frelon.se
  resources:
  - rtlsdrreceivers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - radio.frelon.se
  resources:
  - rtlsdrreceivers/finalizers
  verbs:
  - update
- apiGroups:
  - radio.frelon.se
  resources:
  - rtlsdrreceivers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - watch
