# permissions for end users to edit rtlsdrreceivers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: rtlsdrreceiver-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-radio
    app.kubernetes.io/part-of: k8s-radio
    app.kubernetes.io/managed-by: kustomize
  name: rtlsdrreceiver-editor-role
rules:
- apiGroups:
  - radio.frelon.se
  resources:
  - rtlsdrreceivers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - radio.frelon.se
  resources:
  - rtlsdrreceivers/status
  verbs:
  - get
