apiVersion: radio.frelon.se/v1beta1
kind: RtlSdrReceiver
metadata:
  labels:
    app.kubernetes.io/name: rtlsdrreceiver
    app.kubernetes.io/instance: rtlsdrreceiver-sample
    app.kubernetes.io/part-of: k8s-radio
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-radio
  name: rtlsdrreceiver-sample
spec:
  version: v3
  frequency: "101.9M"
